### ISSUE TITLE
Grayscale is not seen as color.

### ISSUE THREAD

**Issue by lurilandi** [aarhusstadsarkiv/convertool#291]
## From file 10.29.tiff:
```
 0.00550  0.00550  0.00550  0.00550 CMYK OK
 0.01113  0.01113  0.01113  0.01113 CMYK OK
 0.01634  0.01634  0.01634  0.01634 CMYK OK
```
![image](https://user-images.githubusercontent.com/89067733/132695884-d6f97d1a-275a-4ae8-acc0-e5c8a827dd70.png)

Note that on each page, the CMYK values are the same (i.e. black ink).

## From file 15 referat 06-07.tiff:
```
 0.00616  0.00616  0.00616  0.00616 CMYK OK
 0.03840  0.03840  0.03840  0.03840 CMYK OK
 0.04489  0.04489  0.04489  0.04489 CMYK OK
 0.03758  0.03758  0.03758  0.03758 CMYK OK
 0.03019  0.02924  0.03019  0.02924 CMYK OK
```

![image](https://user-images.githubusercontent.com/89067733/132696170-7b1f4e09-24d0-430e-a9a6-a4101f8eefb4.png)

Note that the last page has different CMYK values, since there is color on the page:

![image](https://user-images.githubusercontent.com/89067733/132696441-85df79ba-a59c-4cad-aa77-2fdff507b3e7.png)

Thus, the bit depth is set to 24 and the grayscaled page header is clear.

**Comment by clausjuhl** [comment]
### Links discussing ability to detect greyscale with `gs` in order to select the right tiff bitdepth
- https://stackoverflow.com/questions/42410774/ghostscripts-pdfwrite-to-grayscale-results-in-wrong-graylevel
- https://stackoverflow.com/questions/10474234/ghostscript-grayscale-conversion-still-contains-colors
- https://stackoverflow.com/questions/29861328/how-to-programmatically-convert-a-pdf-to-grayscale-using-only-black-ink
- https://stackoverflow.com/questions/641427/how-do-i-know-if-pdf-pages-are-color-or-black-and-white
- https://tex.stackexchange.com/questions/53493/detecting-all-pages-which-contain-color/61216#61216
- https://www.ghostscript.com/doc/current/Devices.htm#Ink_coverage_output
- https://www.ghostscript.com/doc/current/Devices.htm#TIFF
